name: software  # 与你创建的conda环境名称一致
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - flask==2.3.3
    - requests==2.31.0
    - python-dotenv==1.0.0
    - gunicorn==21.2.0
    - flask-cors==5.0.1